"""Pseudo-experiment generation from a hybrid intensity model."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from .asimov import _draw
from .data import WeightedEvents
from .fnf_runtime import (
    evaluate_fnf_on_support,
    validate_fnf_systematics,
)
from .intensity import IntensityModel, RatioNormalizer
from .protocols import RatioEvaluator, Sampler
from .systematics import RuntimeSystematic


@dataclass
class ToyResult:
    """One unweighted pseudo-dataset and its component Poisson counts."""

    events: WeightedEvents
    point: dict[str, float]
    component_counts: dict[str, int]
    component_expectations: dict[str, float]
    constraint_observations: dict[str, float]

    @property
    def observed_count(self) -> int:
        return self.events.raw_count


class ToyGenerator:
    """Generate component-wise Poisson toys.

    Exact component samplers may be supplied. Otherwise each component is
    generated by importance resampling a fresh pool from the reference flow
    with probability proportional to its normalized process/reference ratio.
    """

    def __init__(
        self,
        *,
        intensity: IntensityModel,
        features: tuple[str, ...] | list[str],
        reference: Sampler | None = None,
        ratios: Mapping[str, RatioEvaluator] | None = None,
        normalizer: RatioNormalizer | None = None,
        component_samplers: Mapping[str, Sampler] | None = None,
        systematics: Mapping[
            str, tuple[RuntimeSystematic, ...] | list[RuntimeSystematic]
        ]
        | None = None,
        fnf_systematics: Mapping[str, Any] | None = None,
    ) -> None:
        self.intensity = intensity
        self.features = tuple(features)
        self.reference = reference
        self.ratios = dict(ratios or {})
        self.normalizer = normalizer
        self.component_samplers = dict(component_samplers or {})
        self.systematics = {
            component: tuple(anchors)
            for component, anchors in (systematics or {}).items()
        }
        parameter_names = {parameter.name for parameter in self.intensity.parameters}
        unknown_components = set(self.systematics).difference(
            self.intensity.component_names
        )
        if unknown_components:
            raise ValueError(
                "Runtime systematics reference unknown components "
                f"{sorted(unknown_components)}."
            )
        for component, anchors in self.systematics.items():
            names = []
            for anchor in anchors:
                if anchor.component != component:
                    raise ValueError(
                        "Runtime systematic component does not match its mapping key."
                    )
                if anchor.parameter not in parameter_names:
                    raise ValueError(
                        "Runtime systematic references unknown parameter "
                        f"{anchor.parameter!r}."
                    )
                names.append(anchor.parameter)
            if len(names) != len(set(names)):
                raise ValueError(
                    f"Component {component!r} repeats a systematic parameter."
                )
        self.fnf_systematics = validate_fnf_systematics(
            self.intensity,
            fnf_systematics,
            anchor_parameters={
                component: tuple(anchor.parameter for anchor in anchors)
                for component, anchors in self.systematics.items()
            },
        )
        missing_direct = set(self.intensity.component_names).difference(
            self.component_samplers
        )
        if missing_direct:
            if self.reference is None or self.normalizer is None:
                raise ValueError(
                    "Components without direct samplers require a reference "
                    "sampler and fixed RatioNormalizer."
                )
            if missing_direct.difference(self.ratios):
                raise ValueError(
                    f"Missing ratio evaluators for {sorted(missing_direct)}."
                )

    @classmethod
    def from_workspace(
        cls,
        path: str | Path,
        *,
        reference: Sampler | None = None,
        ratios: Mapping[str, RatioEvaluator] | None = None,
        component_samplers: Mapping[str, Sampler] | None = None,
        systematics: Mapping[tuple[str, str], RuntimeSystematic] | None = None,
        fnf_systematics: Mapping[str, Any] | None = None,
        fnf_device: str = "cpu",
        onnx_providers: tuple[str, ...] | None = None,
    ) -> ToyGenerator:
        """Bind runtime models to a persisted generative workspace.

        Portable manifest paths and their normalizers are read from the
        workspace. Up/down ratio morphs remain explicit runtime objects.
        Declared FNFs are always loaded from their checked reference, ratio,
        and residual manifests; explicit FNF overrides are rejected.
        """

        from .workspace import load_workspace_model

        model = load_workspace_model(path)
        supplied = dict(systematics or {})
        expected = set(model.systematics)
        if set(supplied) != expected:
            raise ValueError(
                "Workspace runtime systematics must be supplied exactly; "
                f"missing={sorted(expected.difference(supplied))}, "
                f"unknown={sorted(set(supplied).difference(expected))}."
            )
        grouped: dict[str, list[RuntimeSystematic]] = {}
        for key, runtime in supplied.items():
            specification = model.systematics[key]
            if (
                runtime.component != specification.component
                or runtime.parameter != specification.parameter
                or runtime.interpolation != specification.interpolation
                or not np.isclose(runtime.yield_up, specification.yield_up)
                or not np.isclose(runtime.yield_down, specification.yield_down)
            ):
                raise ValueError(
                    f"Runtime systematic {key} conflicts with workspace metadata."
                )
            grouped.setdefault(runtime.component, []).append(runtime)
        configured_fnf = set(model.fnf_manifests)
        parsed_component_samplers = dict(component_samplers or {})
        if configured_fnf:
            if fnf_systematics is not None:
                raise ValueError(
                    "Explicit FNF runtime overrides are not accepted for "
                    "workspace loading; omit fnf_systematics so the checked "
                    "reference, ratio, and residual manifests are reconstructed."
                )
            if reference is not None or ratios is not None:
                raise ValueError(
                    "FNF workspace toys load their reference and ratios from "
                    "the authenticated manifests; custom reference or ratio "
                    "objects are not accepted."
                )
            overlapping_samplers = configured_fnf.intersection(
                parsed_component_samplers
            )
            if overlapping_samplers:
                raise ValueError(
                    "FNF workspace toys cannot use custom nominal component "
                    f"samplers for {sorted(overlapping_samplers)}."
                )
            from .fnf_runtime import load_workspace_fnf_runtime_bundle

            reference, ratios, fnf_systematics = load_workspace_fnf_runtime_bundle(
                model,
                device=fnf_device,
                providers=onnx_providers,
            )
        elif fnf_systematics is not None:
            if fnf_systematics:
                raise ValueError(
                    "Explicit FNF runtime overrides are not accepted for "
                    "workspace loading; omit fnf_systematics so the checked "
                    "reference, ratio, and residual manifests are reconstructed."
                )
            fnf_systematics = {}
        return cls(
            intensity=model.intensity,
            features=model.features,
            reference=reference,
            ratios=ratios,
            normalizer=model.ratio_normalizer,
            component_samplers=parsed_component_samplers,
            systematics=grouped,
            fnf_systematics=fnf_systematics,
        )

    def _draw_component(
        self,
        name: str,
        count: int,
        rng: np.random.Generator,
        *,
        point: Mapping[str, float],
        oversample: int,
        min_pool: int,
        max_pool_rounds: int,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        if count == 0:
            return np.empty((0, len(self.features)), dtype=np.float32), {
                "method": "empty",
                "proposal_pool_size": 0,
                "proposal_pool_ess": None,
                "proposal_pool_rounds": 0,
            }
        active_systematics = self.systematics.get(name, ())
        active_fnf = self.fnf_systematics.get(name)
        if (
            name in self.component_samplers
            and not active_systematics
            and active_fnf is None
        ):
            values = _draw(self.component_samplers[name], count, rng)
            if values.shape[1] != len(self.features):
                raise ValueError(f"Component sampler {name!r} has wrong feature count.")
            return values, {
                "method": "direct",
                "proposal_pool_size": None,
                "proposal_pool_ess": None,
                "proposal_pool_rounds": 0,
            }

        if name not in self.component_samplers:
            assert self.reference is not None
            assert self.normalizer is not None
        if int(max_pool_rounds) < 1:
            raise ValueError("max_pool_rounds must be at least one.")
        if int(oversample) < 1 or int(min_pool) < 1:
            raise ValueError("oversample and min_pool must be positive.")
        pool_size = max(int(min_pool), int(oversample) * count)
        values: np.ndarray | None = None
        probability: np.ndarray | None = None
        pool_ess = 0.0
        fnf_partition: float | None = None
        accepted = False
        for round_index in range(int(max_pool_rounds)):
            if name in self.component_samplers:
                values = _draw(self.component_samplers[name], pool_size, rng)
                raw = np.ones(pool_size, dtype=np.float64)
            else:
                values = _draw(self.reference, pool_size, rng)
                raw = np.asarray(self.ratios[name](values), dtype=np.float64).reshape(
                    -1
                )
                raw = raw / self.normalizer.means[name]
            if len(raw) != pool_size or np.any(raw < 0) or not np.isfinite(raw).all():
                raise ValueError(f"Ratio evaluator {name!r} is invalid.")
            normalized = raw
            for anchor in active_systematics:
                normalized = normalized * anchor.raw_shape(
                    values, point[anchor.parameter]
                )
            if active_fnf is not None:
                evaluation = evaluate_fnf_on_support(
                    active_fnf,
                    values=values,
                    point=point,
                    nominal_shape=normalized,
                    integration_weights=np.ones(len(values), dtype=np.float64),
                )
                normalized = evaluation.shape_ratio
                fnf_partition = evaluation.shape_partition
            total = float(np.sum(normalized))
            if total <= 0:
                raise RuntimeError(f"Ratio {name!r} is zero on the proposal pool.")
            probability = normalized / total
            pool_ess = 1.0 / float(np.sum(probability**2))
            if pool_ess >= min(count, 0.5 * pool_size):
                accepted = True
                break
            if round_index + 1 < int(max_pool_rounds):
                pool_size *= 2
        assert values is not None and probability is not None
        if not accepted:
            raise RuntimeError(
                f"Importance pool for component {name!r} has ESS "
                f"{pool_ess:.3g}, below the required "
                f"{min(count, 0.5 * len(values)):.3g} after "
                f"{int(max_pool_rounds)} rounds. Increase oversample, "
                "min_pool, or max_pool_rounds, or provide a direct sampler."
            )
        indices = rng.choice(len(values), size=count, replace=True, p=probability)
        return values[indices], {
            "method": (
                "component_importance_resampling"
                if name in self.component_samplers
                else "reference_importance_resampling"
            ),
            "proposal_pool_size": int(len(values)),
            "proposal_pool_ess": float(pool_ess),
            "proposal_pool_rounds": int(round_index + 1),
            "fnf_shape_partition": fnf_partition,
            "fnf_parameters": (
                list(active_fnf.parameters) if active_fnf is not None else []
            ),
        }

    def generate(
        self,
        point: Mapping[str, float],
        *,
        seed: int = 0,
        oversample: int = 20,
        min_pool: int = 4096,
        max_pool_rounds: int = 4,
    ) -> ToyResult:
        rng = np.random.default_rng(seed)
        validated_point = self.intensity.validate_point(point)
        expectations = self.intensity.component_yields(validated_point)
        for component, anchors in self.systematics.items():
            for anchor in anchors:
                expectations[component] *= anchor.yield_factor(
                    validated_point[anchor.parameter]
                )
        for component, fnf in self.fnf_systematics.items():
            expectations[component] *= float(fnf.yield_factor(validated_point))
        negative = {name: value for name, value in expectations.items() if value < 0}
        if negative:
            raise ValueError(
                "Component-wise Poisson generation requires non-negative "
                f"expected yields; received {negative}. Signed interference "
                "decompositions need a positive-intensity representation."
            )
        counts = {name: int(rng.poisson(value)) for name, value in expectations.items()}
        constraint_observations = {
            parameter.name: float(
                rng.normal(
                    validated_point[parameter.name],
                    parameter.constraint_sigma,
                )
            )
            for parameter in self.intensity.parameters
            if parameter.constrained
        }
        chunks: list[np.ndarray] = []
        labels: list[np.ndarray] = []
        sampling_diagnostics: dict[str, dict[str, Any]] = {}
        for name in self.intensity.component_names:
            chunk, diagnostics = self._draw_component(
                name,
                counts[name],
                rng,
                point=validated_point,
                oversample=oversample,
                min_pool=min_pool,
                max_pool_rounds=max_pool_rounds,
            )
            chunks.append(chunk)
            labels.append(np.full(len(chunk), name, dtype=object))
            sampling_diagnostics[name] = diagnostics
        if chunks:
            values = np.concatenate(chunks, axis=0)
            components = np.concatenate(labels)
            order = rng.permutation(len(values))
            values = values[order]
            components = components[order]
        else:
            values = np.empty((0, len(self.features)), dtype=np.float32)
            components = np.empty(0, dtype=object)
        events = WeightedEvents(
            values=values,
            weights=np.ones(len(values), dtype=np.float64),
            features=self.features,
            metadata={
                "kind": "hybrid_toy",
                "seed": int(seed),
                "point": dict(validated_point),
                "component_counts": counts,
                "component_expectations": expectations,
                "constraint_observations": constraint_observations,
                "expected_total": float(sum(expectations.values())),
                "observed_total": int(sum(counts.values())),
                "component_sampling_diagnostics": sampling_diagnostics,
            },
            columns={"component": components},
        )
        return ToyResult(
            events=events,
            point=validated_point,
            component_counts=counts,
            component_expectations=expectations,
            constraint_observations=constraint_observations,
        )

    def generate_many(
        self,
        point: Mapping[str, float],
        *,
        n_toys: int,
        seed: int = 0,
        **kwargs: Any,
    ) -> list[ToyResult]:
        sequence = np.random.SeedSequence(seed)
        return [
            self.generate(
                point,
                seed=int(child.generate_state(1, dtype=np.uint32)[0]),
                **kwargs,
            )
            for child in sequence.spawn(int(n_toys))
        ]
